---
title: "Propuestas 2026"
format:
  html:
    title-block-style: default
    title-block-banner: false
---

## Propuestas Generales

1.  Reformar "Introducción a la Matemática" apuntando a la excelencia académica complementando con tutorías.
2.  Garantizar la digitalización del material de todas las materias para aliviar el bolsillo de los estudiantes.
3.  Crear un Sistema de Licencias Especiales para exámenes para estudiantes trabajadores.
4.  Adecuación y mejora de los planes de estudio.
5.  Reforma y reacondicionamiento de espacios de encuentro, estudio y aquellos con valor históricos de la facultad.
6.  Crear y garantizar canales de comunicación institucionales para evitar la monopolización de la información por parte de las agrupaciones.

## Propuestas por carrera

### Contador Público

-   Integradores y parciales en horarios de cursada de cada comisión.

-   Integrar a la carrera la enseñanza de software y programas de uso profesional, evitando la necesidad de pagar cursos por fuera de las cátedras por contenido esencial.

-   Garantizar comisiones de cursado virtual para materias de, al menos, 1er y 2do año. Con prioridad para aquellos estudiantes que trabajan.

### Licenciatura en Administración

-   Especializaciones y ramificaciones de la carrera en el contexto de la actualización de los planes de estudio.

### Licenciatura en Economía

- Solicitar que en Matemática para Economistas III, se dé optimización dinámica.

- Exigir coherencia en el Plan de Estudios. Ej: dar derivación antes de Eco. General.

- Relevamiento de satisfacción estudiantil por materia, con respuestas públicas de carácter anónimo.

- Revisión de contenidos de las materias troncales. Macroeconomía I y II, y Microeconomía II

### Licenciatura en Estadística y Ciencia de Datos

-   Reformar el plan de estudio para evitar la acumulación de contenidos en materias. Este último problema generado en el acortamiento de ambas carreras a 4 años.

-   Simplificar los canales de comunicación y generar medios institucionales para poder estar al día sobre las novedades de ambas carreras.

### Licenciatura en Turismo

- Revisar y actualizar el programa de la materia Estadística Aplicada.

- Agregar la opción de cursado virtual para materias de turnos nocturnos, debido a la doble cursada entre la Siberia y la FCEyE.
